name: Build and Release Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: pyinstaller --onefile --name convert_steam_shortcut convert_steam_shortcut.py

    - name: Create Release and Upload EXE
      uses: softprops/action-gh-release@v2
      with:
        files: dist/convert_steam_shortcut.exe
        tag_name: auto-release-${{ github.sha }}  # Unique tag per commit
        name: Auto Release ${{ github.sha }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
